overrides:
  '@clack/prompts': '$@clack/prompts'
  execa: '$execa'
  jsonwebtoken: '^9'
  yargs: '$yargs'

allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true

onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - skills
